#!/bin/bash 
   
#保存备份个数 
number=3 
#备份保存路径 
backup_dir=/home/mysql_zabbix_backup 
#日期 
dd=`date +%Y%m%d` 
#备份工具 
tool=mysqldump 
#用户名 
username=root 
#密码 
password="abc123"
#将要备份的数据库 
database_name=zabbix 
   
#简单写法  mysqldump -u root -p123456 users > /home/mysqlbackup/users-$filename.dump
$tool -u $username -p$password $database_name > $backup_dir/$database_name-$dd.dump 
   
#写创建备份日志 
echo "create $backup_dir/$database_name-$dd.dump" >> $backup_dir/log.txt 
#   
#找出需要删除的备份 
delfile=`ls -l -crt  $backup_dir/*.dump | awk '{print $9 }' | head -1` 
#   
##判断现在的备份数量是否大于$number 
count=`ls -l -crt  $backup_dir/*.dump | awk '{print $9 }' | wc -l` 
   
if [ $count -gt $number ] 
then 
  rm $delfile  
  #写删除文件日志
  echo "delete $delfile" >> $backup_dir/log.txt 
fi
####zabbix数据库清理
Date=`date -d $(date -d "-60 day" +%Y%m%d) +%s`
echo $Date
$(which mysql) -u${username} -p${password} -e "
use zabbix;
DELETE FROM history WHERE clock < $Date;
optimize table history;
DELETE FROM history_str WHERE clock < $Date;
optimize table history_str;
DELETE FROM history_uint WHERE clock < $Date;
optimize table history_uint;
DELETE FROM trends WHERE clock < $Date;
optimize table trends;
DELETE FROM trends_uint WHERE clock < $Date;
optimize table trends_uint;
DELETE FROM events WHERE clock < $Date;
optimize table events;
"
